---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: raintank_stack::default
    attributes:
      mariadb: 
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
        use_default_repository: true
      grafana: 
        domain: portal.raintank.local
        root_url: http://portal.raintank.local/
        db_type: mysql
        db_host: localhost
        db_port: 3306
        db_name: grafana
        db_user: grafana
        db_password: gnarblatz
      raintank_stack:
        api_key: eyJrIjoiWmZLTktlNHJ0UFFBdWtVdkRyemNiMjZPNFpralA1M3kiLCJuIjoiY29sbGVjdG9yIiwiaWQiOjF9
        ping_port: 9090
        kairosdb: 
          replication_factor: 1
        nginx:
          use_ssl: false
      influxdb:
        version: 0.8.8
      go:
        version: 1.4.2
      nsq:
        version: 0.3.5
        go_version: go1.4.2
        nsqd:
          statsd_interval: 10s
          e2e_processing_latency_window_time: 10s
          e2e_processing_latency_percentile: 0.90,0.99
          mem_queue_size: 0
          sync_every: 4
          max_msg_size: 10024768
          lookupd_tcp_address: []
          msg_timeout: 60s
        nsqadmin:
          lookupd_http_address: []
          nsqd_http_address: []
          statsd_interval: 10s
  - name: capybara
    run_list: 
      - raintank_stack::default
      - raintank_stack::capybara
    attributes:
      mariadb: 
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
        use_default_repository: true
      grafana: 
        domain: portal.raintank.local
        root_url: http://portal.raintank.local/
        db_type: mysql
        db_host: localhost
        db_port: 3306
        db_name: grafana
        db_user: grafana
        db_password: gnarblatz
      raintank_stack:
        api_key: eyJrIjoiWmZLTktlNHJ0UFFBdWtVdkRyemNiMjZPNFpralA1M3kiLCJuIjoiY29sbGVjdG9yIiwiaWQiOjF9
        ping_port: 9090
        kairosdb: 
          replication_factor: 1
        nginx:
          use_ssl: false
      influxdb:
        version: 0.8.8
      go:
        version: 1.4.2
      nsq:
        version: 0.3.5
        go_version: go1.4.2
        nsqd:
          statsd_interval: 10s
          e2e_processing_latency_window_time: 10s
          e2e_processing_latency_percentile: 0.90,0.99
          mem_queue_size: 0
          sync_every: 4
          max_msg_size: 10024768
          lookupd_tcp_address: []
          msg_timeout: 60s
        nsqadmin:
          lookupd_http_address: []
          nsqd_http_address: []
          statsd_interval: 10s
